// portfolioData.js — single source of truth for the artist site (museum + cosmos).
//
// Reads the on-chain catalogue (artistWorks.json, generated by the Alchemy
// fetch) and the human curation layer (portfolioCuration.js), then derives two
// clean structures consumed by BOTH the museum views and the 3D cosmos:
//
//   years    — her 1/1 works grouped by year (institutional convention)
//   projects — her bodies of work / collections, each with scale + world link
//
// Model: she is prolific, so curation is a BLOCKLIST + PROJECTS list, not an
// allowlist.
//   • EXCLUDE_CONTRACTS — art collected from other artists, wrapped tokens,
//     spam airdrops, ENS, etc. Hidden everywhere.
//   • PROJECTS — her named series / generative collections. Pulled OUT of the
//     by-year 1/1 record so they don't flood it, and featured as worlds.
//   • Everything else she minted = a genuine 1/1, listed in Works by year.

import works from './artistWorks.json';
import { PROJECTS, EXCLUDE_CONTRACTS, EXCLUDE_WORK_IDS, EXTRA_WORKS } from './portfolioCuration.js';

const key = w => `${w.chain}|${(w.contract || '').toLowerCase()}`;
const excludeSet = new Set(EXCLUDE_CONTRACTS.map(c => `${c.chain}|${c.address.toLowerCase()}`));
const projectByContract = new Map();
for (const p of PROJECTS) {
  for (const c of p.contracts || []) {
    projectByContract.set(`${c.chain}|${c.address.toLowerCase()}`, p);
  }
}

const cleanTitle = w =>
  (w.title || '').replace(/\s*\|\s*currently.*$/i, '').trim() || `Untitled #${w.tokenId}`;

// Airdrop / phishing spam (e.g. PancakeSwap "$CAKE airdrop" drops) — caught by
// text as well as by contract, so any stragglers never surface anywhere.
const SPAM_RE = /pancake|cakesv4|claimcake|finance-cake|\$cake|cake airdrop|cake token|cake reward/i;
const isSpam = w =>
  SPAM_RE.test(w.title || '') || SPAM_RE.test(w.collection || '') || SPAM_RE.test(w.description || '');

// IPFS / ar:// → http gateway so <img>, <video> and three textures can load them.
// dweb.link (Protocol Labs) supports HTTP range requests, so video artworks
// actually stream/seek — the public ipfs.io gateway is rate-limited and often
// stalls video, which is why grid films wouldn't play.
export const resolveImg = (url = '') =>
  url.startsWith('ipfs://') ? `https://dweb.link/ipfs/${url.slice(7).replace(/^ipfs\//, '')}`
  : url.startsWith('ar://') ? `https://arweave.net/${url.slice(5)}`
  : url;

// Small, fast-loading version for grids + 3D tiles. Routes EVERY remote image
// through the wsrv.nl image CDN — resized to web width and served as WebP — so
// heavy IPFS / Arweave / full-res originals become light thumbnails that all
// load. Data URIs and local (/films, /public) assets pass through untouched.
export const thumb = (url = '', w = 400) => {
  const r = resolveImg(url);
  if (!r) return '';
  if (r.startsWith('data:') || r.startsWith('/')) return r;
  const src = r.replace(/^https?:\/\//, '');
  return `https://wsrv.nl/?url=${encodeURIComponent(src)}&w=${w}&output=webp&q=78&we`;
};

// ── 1/1 WORKS, grouped by year (newest first) ──
const worksByYear = new Map();
for (const w of works) {
  const k = key(w);
  if (excludeSet.has(k)) continue;          // collected / spam — never hers
  if (EXCLUDE_WORK_IDS.has(w.id)) continue; // individually hidden work
  if (isSpam(w)) continue;                  // airdrop / phishing spam
  if (!w.image && !w.thumbnail && !w.animation) continue; // no media → would render a blank tile
  const proj = projectByContract.get(k);
  if (proj && proj.generative) continue;    // large generative collection — shown only as a Project, not by year
  const yr = w.year || 0;
  if (!worksByYear.has(yr)) worksByYear.set(yr, []);
  worksByYear.get(yr).push({ ...w, title: cleanTitle(w) });
}

// Hand-added works (sold pieces the wallet fetch can't see) — slot into their year.
for (const w of EXTRA_WORKS) {
  const yr = w.year || 0;
  if (!worksByYear.has(yr)) worksByYear.set(yr, []);
  worksByYear.get(yr).push({ ...w, title: cleanTitle(w) });
}

export const years = [...worksByYear.entries()]
  .filter(([yr]) => yr)
  .sort((a, b) => b[0] - a[0])
  .map(([year, list]) => ({
    year,
    works: list.sort((a, b) => (b.mintedAt || 0) - (a.mintedAt || 0)),
  }));

// ── PROJECTS / WORLDS ──
// Real on-chain token count per project, so scale stats stay honest.
const projectCounts = new Map();
const projectSamples = new Map();
const projectAll = new Map();           // every work with an image, for "browse all"
for (const w of works) {
  const p = projectByContract.get(key(w));
  if (!p) continue;
  projectCounts.set(p.slug, (projectCounts.get(p.slug) || 0) + 1);
  if (!w.image) continue;
  const tidy = { ...w, title: cleanTitle(w) };
  if (!projectSamples.has(p.slug)) projectSamples.set(p.slug, []);
  const s = projectSamples.get(p.slug);
  if (s.length < 16) s.push(tidy);
  if (!projectAll.has(p.slug)) projectAll.set(p.slug, []);
  projectAll.get(p.slug).push(tidy);
}
// newest first, like the rest of the catalogue
for (const list of projectAll.values()) list.sort((a, b) => (b.mintedAt || 0) - (a.mintedAt || 0));

export const projects = PROJECTS.map(p => ({
  ...p,
  count: p.scale ?? projectCounts.get(p.slug) ?? 0,
  cover: p.cover || projectSamples.get(p.slug)?.[0]?.image || '',
  sample: projectSamples.get(p.slug) || [],
})).sort((a, b) => (b.count || 0) - (a.count || 0));

// ── INK INTERVENTIONS — the constant theme of her practice ──
// Ink isn't one collection: it's the thread that runs through everything she
// makes, from the start to Sotheby's. We surface works that name the theme
// (collection or title carries "ink") spread across her whole timeline.
const isInk = w => /ink/i.test(w.collection || '') || /ink/i.test(w.title || '');
export const inkWorks = works
  .filter(w => !excludeSet.has(key(w)) && !isSpam(w) && w.image && isInk(w))
  .map(w => ({ ...w, title: cleanTitle(w) }))
  .sort((a, b) => (b.mintedAt || 0) - (a.mintedAt || 0));

// ── INK INTERVENTIONS — every work where the artist drew by hand over the image ──
// Matches the named technique ("Ink Intervention") wherever it's recorded —
// title, collection or description — so the whole body of intervened work is
// gathered in one place for the home page. De-duped by id (some contracts repeat).
const isInkIntervention = w =>
  /ink intervention/i.test(w.title || '') ||
  /ink intervention/i.test(w.collection || '') ||
  /ink intervention/i.test(w.description || '');
// Works that mention the technique in passing but aren't Ink Interventions —
// kept in the catalogue, just not surfaced in the home Ink Interventions grid.
const INK_INTERVENTION_EXCLUDE = new Set([
  'ethereum-0x87aceed5e5c1559221339c77d1584a0b26d19ccd-1', // CLUB COUTURE
  'ethereum-0x4b1f58de83b02ad6b88e1d1f47981a47e5bfa235-1', // LOOKING FOR HOPE
  'ethereum-0xa981629a6ef65fb7d64997fa76885ee40819fb99-4', // KISS ME (AI INK INTERVENTIONS film still)
  'ethereum-0xa981629a6ef65fb7d64997fa76885ee40819fb99-3', // STILETTOS (film still)
  'ethereum-0xa981629a6ef65fb7d64997fa76885ee40819fb99-2', // STILETTOS (film still)
  'ethereum-0xa981629a6ef65fb7d64997fa76885ee40819fb99-1', // RUN (film still)
  'ethereum-0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0-46242', // Aeneas and the Obsidian Veil — keep in Works, not an ink intervention
  'ethereum-0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0-46344', // RED BOOTS — keep in Works, not an ink intervention
]);
export const inkInterventions = (() => {
  const seen = new Set();
  return works
    .filter(w => {
      if (excludeSet.has(key(w)) || isSpam(w) || !w.image) return false;
      if (EXCLUDE_WORK_IDS.has(w.id)) return false;     // globally hidden everywhere
      if (INK_INTERVENTION_EXCLUDE.has(w.id)) return false; // not an ink intervention, but kept in catalogue
      if (!isInkIntervention(w)) return false;
      if (seen.has(w.id)) return false;
      seen.add(w.id);
      return true;
    })
    .map(w => ({ ...w, title: cleanTitle(w) }))
    .sort((a, b) => (b.mintedAt || 0) - (a.mintedAt || 0));
})();

// ── DIGITAL COLLAGE — her oldest on-chain practice, running through every year ──
// Collage is a thread across her whole catalogue: named collage collections
// (GRAFFITI COLLAGE, COLLAGE 2025/26, THE GRAFFITI LOOP…) AND early 1/1s that
// only record "collage" in the description (her earliest SuperRare works, 2019-20).
// Match the word anywhere it's recorded, de-duped, respecting the blocklists.
// Paper Dolls is held back (AL); collected collage stays in.
const isCollage = w =>
  /collage/i.test(w.title || '') ||
  /collage/i.test(w.collection || '') ||
  /collage/i.test(w.description || '');
const COLLAGE_EXCLUDE = /paper dolls/i;
// Works whose title carries "collage" but that don't belong in the collage rooms
// (e.g. B&W photographic HEIST pieces). Kept in the catalogue — just not here.
const COLLAGE_EXCLUDE_IDS = new Set([
  'ethereum-0x39447c1b18f497a4d3c029f17c3bbb5a7c75c260-6', // COLLAGE HEIST GANG — B&W photo, not a collage
]);
export const digitalCollage = (() => {
  const seen = new Set();
  return works
    .filter(w => {
      if (excludeSet.has(key(w)) || isSpam(w) || !w.image) return false;
      if (EXCLUDE_WORK_IDS.has(w.id)) return false;
      if (COLLAGE_EXCLUDE.test(w.collection || '') || COLLAGE_EXCLUDE.test(w.title || '')) return false;
      if (COLLAGE_EXCLUDE_IDS.has(w.id)) return false;
      if (isInkIntervention(w)) return false;   // an Ink Intervention belongs in the ink room, not the collage rooms
      if (/\bink\b/i.test(w.title || '') || /\bink\b/i.test(w.collection || '')) return false; // ink works belong in the ink hall
      if (!isCollage(w)) return false;
      if (seen.has(w.id)) return false;
      seen.add(w.id);
      return true;
    })
    .map(w => ({ ...w, title: cleanTitle(w) }))
    .sort((a, b) => (b.mintedAt || 0) - (a.mintedAt || 0));
})();

// ── GRAFFITI STILETTOS — her on-chain "Graffiti Stiletto" 1/1s ──
// A distinct body of work (NFT FOMO, PIN-UP, OLD MONEY CORRUPTS, I ❤️ NFTS,
// ETHEREUM, SHARP, PURPLE, LACE, BOOTS, GREEN…). Gathered here for the front
// "Hall of Graffiti Stilettos" in the entrance corridor. Matches the title
// "Graffiti Stiletto(s)" wherever it's recorded, de-duped, respecting blocklists.
const isGraffitiStiletto = w =>
  /graffiti\s*stil+et+o/i.test(w.title || '') ||
  /graffiti\s*stil+et+o/i.test(w.collection || '');
export const graffitiStilettos = (() => {
  const seen = new Set();
  return works
    .filter(w => {
      if (excludeSet.has(key(w)) || isSpam(w) || !w.image) return false;
      if (EXCLUDE_WORK_IDS.has(w.id)) return false;
      if (!isGraffitiStiletto(w)) return false;
      if (seen.has(w.id)) return false;
      seen.add(w.id);
      return true;
    })
    .map(w => ({ ...w, title: cleanTitle(w) }))
    .sort((a, b) => (b.mintedAt || 0) - (a.mintedAt || 0));
})();

// ── Moving-image works (animation_url) — used to keep the home page alive ──
export const videoWorks = works
  .filter(w => w.animation && !excludeSet.has(key(w)) && !isSpam(w))
  .map(w => ({ ...w, title: cleanTitle(w) }))
  .sort((a, b) => (b.mintedAt || 0) - (a.mintedAt || 0));

// ── lookups ──
const allWorks = years.flatMap(y => y.works);
export const getWork = id => allWorks.find(w => w.id === id);
export const getProject = slug => projects.find(p => p.slug === slug);
// Every imaged work in a collection (newest first) — for the "browse all" grid.
export const getProjectWorks = slug => projectAll.get(slug) || [];

export const totals = {
  works: allWorks.length,
  projects: projects.length,
  projectTokens: projects.reduce((n, p) => n + (p.count || 0), 0),
  firstYear: years.length ? years[years.length - 1].year : null,
  lastYear: years.length ? years[0].year : null,
};
